# scripts/catalog.py

MONOGRAPH_ENTRIES = [
    # Module 02: Antipsychotics & Dopamine Pathways
    (34, 35, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (36, 37, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (38, 39, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (40, 41, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (42, 43, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (44, 45, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (46, 47, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (48, 49, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (50, 51, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (52, 53, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (54, 55, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (56, 57, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (58, 59, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Second-Generation Antipsychotics (SGAs / Atypicals)', 'sg-sga'),
    (60, 61, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (62, 63, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'Third-Generation & Novel Muscarinic Antipsychotics', 'sg-third-gen'),
    (64, 65, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'First-Generation Antipsychotics (FGAs / Typicals)', 'sg-fga'),
    (66, 67, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'First-Generation Antipsychotics (FGAs / Typicals)', 'sg-fga'),
    (68, 69, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'First-Generation Antipsychotics (FGAs / Typicals)', 'sg-fga'),
    (70, 71, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'First-Generation Antipsychotics (FGAs / Typicals)', 'sg-fga'),
    (72, 73, 'antipsychotics', 'Antipsychotics & Dopamine Pathways', 'First-Generation Antipsychotics (FGAs / Typicals)', 'sg-fga'),

    # Module 03: Antidepressants & Serotonergic Systems
    (88, 89, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (90, 91, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (92, 93, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (94, 95, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (96, 97, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (98, 99, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Selective Serotonin Reuptake Inhibitors (SSRIs)', 'sg-ssri'),
    (100, 101, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)', 'sg-snri'),
    (102, 103, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)', 'sg-snri'),
    (104, 105, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)', 'sg-snri'),
    (106, 107, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)', 'sg-snri'),
    (108, 109, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Multimodal Serotonergic Agents (SPARI / SMS)', 'sg-multimodal'),
    (110, 111, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Multimodal Serotonergic Agents (SPARI / SMS)', 'sg-multimodal'),
    (112, 113, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'NDRI & Serotonin Antagonist / Reuptake Modulators', 'sg-ndri'),
    (114, 115, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'NDRI & Serotonin Antagonist / Reuptake Modulators', 'sg-ndri'),
    (116, 117, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'NDRI & Serotonin Antagonist / Reuptake Modulators', 'sg-ndri'),
    (118, 119, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Multimodal Serotonergic Agents (SPARI / SMS)', 'sg-multimodal'),
    (120, 121, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)', 'sg-snri'),
    (122, 123, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Tricyclic Antidepressants (TCAs)', 'sg-tca'),
    (124, 125, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Tricyclic Antidepressants (TCAs)', 'sg-tca'),
    (126, 127, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Monoamine Oxidase Inhibitors (MAOIs)', 'sg-maoi'),

    # Module 04: Mood Stabilizers & Bipolar Disorders
    (142, 143, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Lithium Carbonate & Salts', 'sg-lithium'),
    (144, 145, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (146, 147, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (148, 149, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (150, 151, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (152, 153, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (154, 155, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (156, 157, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (158, 159, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (160, 161, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (162, 163, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (164, 165, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (166, 167, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (168, 169, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (170, 171, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (172, 173, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (174, 175, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (176, 177, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Atypical Antipsychotics in Bipolar Disorder', 'sg-bipolar-antipsychotics'),
    (178, 179, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Anticonvulsant Mood Stabilizers', 'sg-anticonvulsants'),
    (180, 181, 'mood-stabilizers', 'Mood Stabilizers & Bipolar Disorders', 'Lithium Carbonate & Salts', 'sg-lithium'),

    # Module 05: Anxiolytics, Sedatives & Hypnotics
    (196, 197, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (198, 199, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (200, 201, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (202, 203, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (204, 205, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (206, 207, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (208, 209, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (210, 211, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (212, 213, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (214, 215, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Benzodiazepines (BZDs)', 'sg-bzd'),
    (216, 217, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-Benzodiazepine Hypnotics (Z-Drugs)', 'sg-z-drugs'),
    (218, 219, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-Benzodiazepine Hypnotics (Z-Drugs)', 'sg-z-drugs'),
    (220, 221, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-Benzodiazepine Hypnotics (Z-Drugs)', 'sg-z-drugs'),
    (222, 223, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Dual Orexin Receptor Antagonists (DORAs)', 'sg-dora'),
    (224, 225, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Dual Orexin Receptor Antagonists (DORAs)', 'sg-dora'),
    (226, 227, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Dual Orexin Receptor Antagonists (DORAs)', 'sg-dora'),
    (228, 229, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Dual Orexin Receptor Antagonists (DORAs)', 'sg-dora'),
    (230, 231, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-BZD Anxiolytics & Gabapentinoids', 'sg-non-bzd-anx'),
    (232, 233, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-BZD Anxiolytics & Gabapentinoids', 'sg-non-bzd-anx'),
    (234, 235, 'anxiolytics', 'Anxiolytics, Sedatives & Hypnotics', 'Non-BZD Anxiolytics & Gabapentinoids', 'sg-non-bzd-anx'),

    # Module 06: ADHD, Wakefulness & Cognitive Enhancers
    (250, 251, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (252, 253, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (254, 255, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (256, 257, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (258, 259, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (260, 261, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (262, 263, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (264, 265, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Central Nervous System Stimulants (MPH & AMPH)', 'sg-adhd-stimulants'),
    (266, 267, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Non-Stimulant ADHD Therapeutics', 'sg-adhd-non-stimulants'),
    (268, 269, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Non-Stimulant ADHD Therapeutics', 'sg-adhd-non-stimulants'),
    (270, 271, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Non-Stimulant ADHD Therapeutics', 'sg-adhd-non-stimulants'),
    (272, 273, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Non-Stimulant ADHD Therapeutics', 'sg-adhd-non-stimulants'),
    (274, 275, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Wakefulness-Promoting Agents & Eugeroics', 'sg-wakefulness'),
    (276, 277, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Wakefulness-Promoting Agents & Eugeroics', 'sg-wakefulness'),
    (278, 279, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Wakefulness-Promoting Agents & Eugeroics', 'sg-wakefulness'),
    (280, 281, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Wakefulness-Promoting Agents & Eugeroics', 'sg-wakefulness'),
    (282, 283, 'adhd', 'ADHD, Wakefulness & Cognitive Enhancers', 'Wakefulness-Promoting Agents & Eugeroics', 'sg-wakefulness'),

    # Module 07: Substance Use Disorders & Addiction Medicine
    (304, 305, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Opioid Use Disorder Therapeutics (MAT)', 'sg-oud'),
    (306, 307, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Opioid Use Disorder Therapeutics (MAT)', 'sg-oud'),
    (308, 309, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Opioid Use Disorder Therapeutics (MAT)', 'sg-oud'),
    (310, 311, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Opioid Use Disorder Therapeutics (MAT)', 'sg-oud'),
    (312, 313, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (314, 315, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Alcohol Use Disorder Therapeutics', 'sg-aud'),
    (316, 317, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Alcohol Use Disorder Therapeutics', 'sg-aud'),
    (318, 319, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Alcohol Use Disorder Therapeutics', 'sg-aud'),
    (320, 321, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Alcohol Use Disorder Therapeutics', 'sg-aud'),
    (322, 323, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Nicotine Cessation Pharmacotherapies', 'sg-smoking'),
    (324, 325, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Nicotine Cessation Pharmacotherapies', 'sg-smoking'),
    (326, 327, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Nicotine Cessation Pharmacotherapies', 'sg-smoking'),
    (328, 329, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (330, 331, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (332, 333, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (334, 335, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (336, 337, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (338, 339, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (340, 341, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),
    (342, 343, 'substance-use', 'Substance Use Disorders & Addiction Medicine', 'Acute Toxidrome & Overdose Resuscitation', 'sg-overdose-rescue'),

    # Module 08: Neuropsychiatry & Movement Disorders
    (358, 359, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Centrally-Acting Anticholinergics & Pro-Dopaminergic', 'sg-eps-anticholinergic'),
    (360, 361, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Centrally-Acting Anticholinergics & Pro-Dopaminergic', 'sg-eps-anticholinergic'),
    (362, 363, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Centrally-Acting Anticholinergics & Pro-Dopaminergic', 'sg-eps-anticholinergic'),
    (364, 365, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Centrally-Acting Anticholinergics & Pro-Dopaminergic', 'sg-eps-anticholinergic'),
    (366, 367, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Centrally-Acting Anticholinergics & Pro-Dopaminergic', 'sg-eps-anticholinergic'),
    (368, 369, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Beta-Adrenergic Blockers & Akathisia Interventions', 'sg-akathisia-beta'),
    (370, 371, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Beta-Adrenergic Blockers & Akathisia Interventions', 'sg-akathisia-beta'),
    (372, 373, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (374, 375, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'VMAT2 Inhibitors (Tardive Dyskinesia)', 'sg-vmat2'),
    (376, 377, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'VMAT2 Inhibitors (Tardive Dyskinesia)', 'sg-vmat2'),
    (378, 379, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'VMAT2 Inhibitors (Tardive Dyskinesia)', 'sg-vmat2'),
    (380, 381, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (382, 383, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (384, 385, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (386, 387, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (388, 389, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (390, 391, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (392, 393, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (394, 395, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),
    (396, 397, 'neuropsychiatry', 'Neuropsychiatry & Movement Disorders', 'Catatonia, NMS & Tourette Specialists', 'sg-catatonia-movement'),

    # Module 09: Special Populations (Novel Neuroactive Steroids)
    (412, 413, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Rapid-Acting NMDA Modulators & Neurosteroids', 'sg-neurosteroids'),
    (414, 415, 'antidepressants', 'Antidepressants & Serotonergic Systems', 'Rapid-Acting NMDA Modulators & Neurosteroids', 'sg-neurosteroids'),

    # Module 10: Neurology Essentials for Clinical Psychiatry
    (466, 467, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (468, 469, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (470, 471, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (472, 473, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (474, 475, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (476, 477, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (478, 479, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (480, 481, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (482, 483, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (484, 485, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (486, 487, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (488, 489, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),
    (490, 491, 'neurology', 'Neurology Essentials for Psychiatry', 'Cholinesterase Inhibitors & NMDA Neuroprotection', 'sg-dementia-memory'),
    (492, 493, 'neurology', 'Neurology Essentials for Psychiatry', 'Cholinesterase Inhibitors & NMDA Neuroprotection', 'sg-dementia-memory'),
    (494, 495, 'neurology', 'Neurology Essentials for Psychiatry', 'Cholinesterase Inhibitors & NMDA Neuroprotection', 'sg-dementia-memory'),
    (496, 497, 'neurology', 'Neurology Essentials for Psychiatry', 'Cholinesterase Inhibitors & NMDA Neuroprotection', 'sg-dementia-memory'),
    (498, 499, 'neurology', 'Neurology Essentials for Psychiatry', 'Dopamine Agonists & Parkinsonian Therapies', 'sg-parkinson-motor'),
    (500, 501, 'neurology', 'Neurology Essentials for Psychiatry', 'Dopamine Agonists & Parkinsonian Therapies', 'sg-parkinson-motor'),
    (502, 503, 'neurology', 'Neurology Essentials for Psychiatry', 'Neurobehavioral & Headache Therapies', 'sg-neurobehavioral'),
    (504, 505, 'neurology', 'Neurology Essentials for Psychiatry', 'Antiseizure Medications & SV2A / Channel Blockers', 'sg-seizure-sv2a'),

    # Module 11: Emergency Antidotes & Interventional Psychopharmacology
    (520, 521, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Rapid Interventional Infusions & Ketamines', 'sg-rapid-infusions'),
    (522, 523, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'ECT Anesthetic & Neuromuscular Agents', 'sg-ect-anesthesia'),
    (524, 525, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'ECT Anesthetic & Neuromuscular Agents', 'sg-ect-anesthesia'),
    (526, 527, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (528, 529, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (530, 531, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (532, 533, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (534, 535, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (536, 537, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Critical Care, Encephalopathy & Metabolic Rescue', 'sg-organ-protection'),
    (538, 539, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Critical Care, Encephalopathy & Metabolic Rescue', 'sg-organ-protection'),
    (540, 541, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Rapid Interventional Infusions & Ketamines', 'sg-rapid-infusions'),
    (542, 543, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Rapid Interventional Infusions & Ketamines', 'sg-rapid-infusions'),
    (544, 545, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (546, 547, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (548, 549, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (550, 551, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes'),
    (552, 553, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Critical Care, Encephalopathy & Metabolic Rescue', 'sg-organ-protection'),
    (554, 555, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Critical Care, Encephalopathy & Metabolic Rescue', 'sg-organ-protection'),
    (556, 557, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Critical Care, Encephalopathy & Metabolic Rescue', 'sg-organ-protection'),
    (558, 559, 'antidotes-interventional', 'Emergency Antidotes & Interventional Psychopharmacology', 'Targeted Toxidrome Antidotes & Receptor Blockers', 'sg-specific-antidotes')
]
